### ISSUE TITLE
May I request a backport to 1.7.10?

### ISSUE THREAD

**Issue by obsidian29** [JLChnToZ/MCCustomSkinLoader#249] opened 2023-04-11 07:17 UTC
### Describe the feature

I love this mod and I always use it if it's available. Not only does it allow me to use my own skin when my internet cuts out, but I sometimes like to roleplay as different characters of mine or different universes, and I create skins for them and use CustomSkinLoader to use those skins ingame. But there is no version for 1.7.10, which is one of the versions I play.

I understand if it is too much work and you are not willing, but I would very much love to have this mod accessible on 1.7.10. Specifically I play with Fisk's Heroes which is exclusive to 1.7.10 at the moment, and I would like to play as the heroes with the powers supplied by that mod using the skins I have created for those characters.

Either way, thank you very much for the mod, it has truly increased my enjoyment of the game in a number of ways.

### Before submitting a suggestion

- [x] This feature doesn't already exist in the client. (I have checked every module and their settings on the **latest dev build**)

- [x] This wasn't already suggested. (I have searched suggestions on GitHub and read the FAQ)

**Comment by ZekerZhayard** [comment] 2023-04-11 07:30
https://www.curseforge.com/minecraft/mc-mods/compatibilitylayerforcustomskinloader

**Comment by obsidian29** [comment] 2023-04-11 18:58
Oh, thanks! I hadn't seen that. This is perfect, thank you!

Do I just drop it in the mods folder along with CSL? And what version of the CSL jar do I need for it? Thanks!

**Comment by 8MiYile** [comment] 2023-04-12 05:16
@obsidian29 Try using ForgeLegacy and if that doesn't work, use ForgeActive
If the problem is resolved, please remember to close the issue manually

This is the list of Mods that I use and the client has the correct work
```
_unimixins-all-1.7.10-0.1.6.jar
CompatibilityLayerForCustomSkinLoader-ALPHA-11.jar
CustomSkinLoader_ForgeLegacy-<latest>.jar
```

**Comment by obsidian29** [comment] 2023-04-14 02:05
Thank you, that got it working! Hilariously enough CSL turned out to be incompatible with Fisk's Superheroes. One of those bugs that just makes you laugh. XD Thank you, any time I'm using 1.7.10 (and not Fisk's Heroes XD) I'll use these.

**Closed as completed** 2023-04-14 02:05 UTC
Labels: enhancement
